import type {
  NativeFunction,
  NativeModuleEntry,
  NativeParam,
  NativeType,
} from "./manifest.ts";
import { symbolFor } from "./manifest.ts";

function namespaceFor(slug: string): string {
  return `flypath::${slug}`;
}

function cxxType(type: NativeType): string {
  switch (type.kind) {
    case "void":
      return "void";
    case "boolean":
      return "bool";
    case "number":
      return "double";
    case "string":
      return "std::string";
    case "bytes":
      return "std::vector<uint8_t>";
    case "array":
      return `std::vector<${cxxType(type.element)}>`;
    case "optional":
      return `std::optional<${cxxType(type.value)}>`;
    case "struct":
    case "enum":
      return type.name;
  }
}

function caseName(value: string): string {
  const name = value.replace(/[^A-Za-z0-9]+/g, "_");
  return /^[0-9]/.test(name) ? `_${name}` : name;
}

function parameter(param: NativeParam): string {
  const type = cxxType(param.type);
  const byValue =
    param.type.kind === "boolean" ||
    param.type.kind === "number" ||
    param.type.kind === "enum";
  return byValue ? `${type} ${param.name}` : `const ${type}& ${param.name}`;
}

function signature(entry: NativeFunction): string {
  const params = entry.params.map(parameter).join(", ");
  const result = entry.async
    ? `flypath::Promise<${cxxType(entry.result)}>`
    : cxxType(entry.result);
  return `${result} ${entry.name}(${params});`;
}

function structDeclaration(name: string, fields: NativeParam[]): string {
  return [
    `struct ${name} {`,
    ...fields.map((field) => `  ${cxxType(field.type)} ${field.name};`),
    "};",
  ].join("\n");
}

function enumDeclaration(name: string, values: string[]): string {
  return [
    `enum class ${name} {`,
    ...values.map((value) => `  ${caseName(value)},`),
    "};",
  ].join("\n");
}

function support(module: NativeModuleEntry): string[] {
  const parts: string[] = [];

  for (const struct of module.structs) {
    parts.push(
      [
        `inline void encode(FlypathOutRef out, const ${struct.name}& value) {`,
        "  FlypathOutRef object = flypath_out_object(out);",
        ...struct.fields.map(
          (field) =>
            `  flypath::encode(flypath_out_field(object, ${JSON.stringify(
              field.name,
            )}), value.${field.name});`,
        ),
        "}",
        "",
        `inline void decode(FlypathValueRef value, ${struct.name}& out) {`,
        ...struct.fields.map(
          (field) =>
            `  flypath::decode(flypath_field(value, ${JSON.stringify(
              field.name,
            )}), out.${field.name});`,
        ),
        "}",
      ].join("\n"),
    );
  }

  for (const entry of module.enums) {
    parts.push(
      [
        `inline void encode(FlypathOutRef out, ${entry.name} value) {`,
        "  switch (value) {",
        ...entry.values.map(
          (value) =>
            `    case ${entry.name}::${caseName(value)}: flypath::encode(out, std::string(${JSON.stringify(
              value,
            )})); return;`,
        ),
        "  }",
        "}",
        "",
        `inline void decode(FlypathValueRef value, ${entry.name}& out) {`,
        "  std::string text;",
        "  flypath::decode(value, text);",
        ...entry.values.map(
          (value) =>
            `  if (text == ${JSON.stringify(value)}) { out = ${entry.name}::${caseName(
              value,
            )}; return; }`,
        ),
        "}",
      ].join("\n"),
    );
  }

  return parts;
}

export function generateCxxHeader(module: NativeModuleEntry): string {
  const space = namespaceFor(module.slug);
  const parts = [
    ...module.structs.map((entry) =>
      structDeclaration(entry.name, entry.fields),
    ),
    ...module.enums.map((entry) => enumDeclaration(entry.name, entry.values)),
    ...support(module),
    ...module.functions.map(signature),
  ];

  return `// Generated by flypath from ${module.source}. Do not edit.
#pragma once

#include <FlypathCpp.h>

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace ${space} {

${parts.join("\n\n")}

}  // namespace ${space}
`;
}

export function generateCxxAdapters(modules: NativeModuleEntry[]): string {
  const includes = modules.map(
    (module) => `#include "${module.base}.flypath.h"`,
  );

  const bodies = modules.flatMap((module) =>
    module.functions.map((entry) => {
      const space = namespaceFor(module.slug);
      const symbol = symbolFor(module.slug, entry.name);
      const reads = entry.params.map(
        (param, index) =>
          `  ${cxxType(param.type)} ${param.name} = flypath::read<${cxxType(
            param.type,
          )}>(flypath_at(args, ${index}));`,
      );
      const call = `${space}::${entry.name}(${entry.params
        .map((param) => param.name)
        .join(", ")})`;

      if (entry.async) {
        return [
          `void ${symbol}(FlypathValueRef args, FlypathPromiseRef promise) {`,
          ...reads,
          `  ${call}.bind(promise);`,
          "}",
        ].join("\n");
      }

      if (entry.result.kind === "void") {
        return [
          `void ${symbol}(FlypathValueRef args, FlypathOutRef result) {`,
          ...reads,
          "  (void)result;",
          `  ${call};`,
          "}",
        ].join("\n");
      }

      return [
        `void ${symbol}(FlypathValueRef args, FlypathOutRef result) {`,
        ...reads,
        `  flypath::encode(result, ${call});`,
        "}",
      ].join("\n");
    }),
  );

  return `#include <FlypathAbi.h>
#include <FlypathCpp.h>

${includes.join("\n")}

extern "C" {

${bodies.join("\n\n")}

}
`;
}

export function clangdConfig(includes: string[]): string {
  const flags = [
    "-xc++",
    "-std=c++20",
    ...includes.map((value) => `-I${value}`),
  ];
  return `CompileFlags:
  Add: [${flags.map((flag) => JSON.stringify(flag)).join(", ")}]
`;
}
